{
 "title": "Number of calls to endpoints",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_status_phase{namespace=~\"$namespace\",phase=\"Running\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "APP LAUNCH COUNT",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(app_start_count_total{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "CALLS TO THE SERVER LAST HOUR",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(server_requests_total{namespace=\"$namespace\"}) - sum(min_over_time(server_requests_total{namespace=\"$namespace\"} [1h]))"
    }
   ]
  },
  {
   "title": "CALLS TO / LAST HOUR",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(main_requests_total{namespace=\"$namespace\"}) - sum(min_over_time(main_requests_total{namespace=\"$namespace\"} [1h]))"
    }
   ]
  },
  {
   "title": "CALLS TO /BYE LAST HOUR",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(bye_requests_total{namespace=\"$namespace\"}) - sum(min_over_time(bye_requests_total{namespace=\"$namespace\"} [1h]))"
    }
   ]
  },
  {
   "title": "CALLS TO /JOKE LAST HOUR",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(joke_requests_total{namespace=\"$namespace\"}) - sum(min_over_time(joke_requests_total{namespace=\"$namespace\"} [1h]))"
    }
   ]
  },
  {
   "title": "NUMBER OF CALLS TO /HEALTH ENDPOINT IN THE LAST HOUR",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "healthcheck_requests_total{namespace=\"$namespace\"} - min_over_time(healthcheck_requests_total{namespace=\"$namespace\"} [1h])"
    }
   ]
  },
  {
   "title": "CPU USAGE VS CPU REQUEST",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\"}) by (pod)"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\", pod=\"$pod\"}) by (pod)"
    }
   ]
  }
 ]
}