name: Release-build

on:
  workflow_run:
    workflows:
      - "Test"
    branches: [ main ]
    types:
      - completed

permissions:
  contents: write
  packages: write
  issues: read
  pull-requests: read

jobs:
  semantic-release:
    if: "${{ github.event.workflow_run.conclusion == 'success' && !contains(github.event.commits[0].message, 'chore(release):') }}"
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login in GHCR
        uses: docker/login-action@v1
        id: configure-login-ghcr
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        id: configure-login-dockerhub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup yq
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
        env:
          YQ_VERSION: "3.4.1"

      - name: Setup helm-docs
        run: |
          mkdir /tmp/helm-docs
          wget -qO /tmp/helm-docs/helm-docs_${HELM_DOCS_VERSION}_Linux_x86_64.tar.gz https://github.com/norwoodj/helm-docs/releases/download/v${HELM_DOCS_VERSION}/helm-docs_${HELM_DOCS_VERSION}_Linux_x86_64.tar.gz
          tar -xf /tmp/helm-docs/helm-docs_${HELM_DOCS_VERSION}_Linux_x86_64.tar.gz -C /tmp/helm-docs
          sudo mv /tmp/helm-docs/helm-docs /usr/local/bin/helm-docs
          sudo chmod +x /usr/local/bin/helm-docs
        env:
          HELM_DOCS_VERSION: "1.5.0"

      - name: Create empty semantic_release_version.txt file
        run: touch semantic_release_version.txt

      - name: Release
        id: semantic_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --debug

      - name: Get the version
        id: get_version
        run: |
          echo VERSION=$(cat semantic_release_version.txt) >> $GITHUB_ENV

      - name: Build and push Docker image
        if: ${{ env.VERSION != '' }}
        run: make publish
        env:
          VERSION: ${{ env.VERSION }}

    outputs:
      version: ${{ env.VERSION }}
